export enum MoviesActionType {
  GET_MOVIES = 'get_movies',
  GET_MOVIES_SUCCESS = 'movies_get_success',
  GET_MOVIES_ERROR = 'movies_get_error',
  SEARCH_MOVIES = 'search_movies',
  SEARCH_MOVIES_SUCCESS = 'movies_search_success',
  SEARCH_MOVIES_ERROR = 'movies_search_error',
  UPDATE_POSTER = 'update_poster',
  UPDATE_POSTER_SUCCESS = 'update_poster_success',
  UPDATE_POSTER_ERROR = 'update_poster_error',
  UPDATE_MOVIE = 'update_movie',
  UPDATE_MOVIE_SUCCESS = 'update_movie_success',
  UPDATE_MOVIE_ERROR = 'update_movie_error',
  ADD_MOVIE = 'add_movie',
  ADD_MOVIE_SUCCESS = 'add_movie_success',
  ADD_MOVIE_ERROR = 'add_movie_error',
  DELETE_MOVIE = 'delete_movie',
  DELETE_MOVIE_SUCCESS = 'delete_movie_success',
  DELETE_MOVIE_ERROR = 'delete_movie_error',
  FILTER_MOVIES = 'filter_movies',
  FILTER_MOVIES_SUCCESS = 'filter_movies_success',
  FILTER_MOVIES_ERROR = 'filter_movies_error',
  SORT_MOVIES = 'sort_movies',
  SORT_MOVIES_SUCCESS = 'sort_movies_success',
  SORT_MOVIES_ERROR = 'sort_movies_error'
}
